### ISSUE TITLE
README should not recommend ufo

### ISSUE THREAD

**Issue by moritz** [jonathanstowe/Test-META#11]
ufo doesn't work, and isn't necessary since we precompile anyway.

**Comment by jonathanstowe** [comment]
Hi,
I've been removing the references to ufo as I make new releases of the modules. I'm not entirely convinced that anyone is actually using any of them, let alone read the README,

**Comment by moritz** [comment]
Well, we had somebody on #perl6 asking why his ufo is broken, and he pointed to this very README as the source of his information.

So this is not a theoretical complaint, but from observing actual misdirection.

**Comment by jonathanstowe** [comment]
Fine :)  Another release then.
