### ISSUE TITLE
Report invalid "*" versions

### ISSUE THREAD

**Issue by zoffixznet** [jonathanstowe/Test-META#28]
if a module has "*" as version in META file, it should be reported as a meta error. Per: https://irclog.perlgeek.de/perl6-dev/2017-06-16#i_14743456

```
eveo 	Well, it's using "*" as a version number
TimToady 	that's not really a valid version number; it's a valid version number matcher
TimToady 	wildcards should not be part of the identity of a module; they should only be used where dependencies are being checked
```

**Comment by jonathanstowe** [comment]
Sounds sensible to me.  I'll try to have a look this evening.

**Comment by jonathanstowe** [comment]
I'm going to make the test "shouldn't have any '*' as part of the version"

**Comment by jonathanstowe** [comment]
Okay I didn't leave it till the evening.
