### ISSUE TITLE
meta-ok seems to ignore some data

### ISSUE THREAD

**Issue by tbrowder** [jonathanstowe/Test-META#29]
meta-ok seems to report the same ok results regardless of whether I add :relaxed-name or not or whether I have a 'v' in version.  Also, the word 'hypen' should be spelled 'hyphen';

Given pertinent parts of my META6.json file:

```
    "name" : "Geo::Ellipsoid",
    "version" : "0.1.0",
    "source-url" : "git://github.com/tbrowder/Geo-Ellipsoid-Perl6.git",
    "support"     : {
        "bugtracker" : "https://github.com/tbrowder/Geo-Ellipsoid-Perl6/issues"
    },
    "provides" : {
	"Geo::Ellipsoid"        : "lib/Geo/Ellipsoid.pm6",
	"Geo::Ellipsoid::Utils" : "lib/Geo/Ellipsoid/Utils.pm6"
    },
```

I get the message

```
1..1
    ok 1 - have a META file
    ok 2 - META parses okay
    ok 3 - have all required entries
    ok 4 - 'provides' looks sane
    ok 5 - Optional 'authors' and not 'author'
    ok 6 - License is correct
    ok 7 - name has a hypen rather than '::' (if this is intentional please pass :relaxed-name to meta-ok)
    ok 8 - no 'v' in version strings (meta-version greater than 0)
    ok 9 - version is present and doesn't have an asterisk
    ok 10 - have usable source
    1..10
ok 1 - Project META file is good
```

**Comment by jonathanstowe** [comment]
Er, the '```relaxed-name``` only applies to the ```name``` attribute.  The 'v' in version test only applies if the META file contains ```meta-version``` and that is greater than 0. 

So  if you had, for example:

```
{
    "meta-version" : 1,
    "perl" : "6.c",
    "description" : "something",
    "name" : "Geo::Ellipsoid",
    "version" : "v0.1.0",
    "source-url" : "git://github.com/tbrowder/Geo-Ellipsoid-Perl6.git",
    "support"     : {
        "bugtracker" : "https://github.com/tbrowder/Geo-Ellipsoid-Perl6/issues"
    },
    "provides" : {
	"Geo::Ellipsoid"        : "lib/Geo/Ellipsoid.pm6",
	"Geo::Ellipsoid::Utils" : "lib/Geo/Ellipsoid/Utils.pm6"
    }
}
```
This would indeed fail.  The reason that the result is contingent on the ```meta-version``` is that in the spec it originally had the 'v' in the version and it seemed unfair to fail something that was following the given example at the time, (also I believe both *zef* and *panda* work around the presence of the 'v' in a similar way that META6 does.)

Or am I completely misunderstanding?

**Comment by tbrowder** [comment]
I think I’m confusing the test description with what is actually happening—I shouln’t expect the description to change regardless of ok or not.  A long time ago I did a fork to work on a PR to propose rewording the descriptions but got sidetracked onto more exciting things. Sorry for the noise.
