### ISSUE TITLE
Failure to detect wrong paths in `provides`

### ISSUE THREAD

**Issue by zoffixznet** [jonathanstowe/Test-META#4]
If the files listed in `provides` section contain, say `/lib/foo.pm` then the `Test::META` will OK them if `lib/foo.pm` exists, but panda will fail to install them.

This is due to `.child` method accepting the `/` and still returning true:
```
<Zoffix> m: say '/'.IO.child('dev').e; say '/'.IO.child('/dev').e
<camelia> rakudo-moar 3568c1: OUTPUT«True␤True␤»
```

**Comment by jonathanstowe** [comment]
Hadn't even occurred to me.  Thanks.
