### ISSUE TITLE
author/authors section

### ISSUE THREAD

**Issue by zoffixznet** [jonathanstowe/Test-META#5]
According to [the spec](http://design.perl6.org/S22.html#authors), only `authors` field containing an array is valid. Some people use `author : "Whatever"` instead and `Test::META` does not detect that as an issue.

Perhaps it could?

**Comment by jonathanstowe** [comment]
Yeah, I think I marked "author" as "customary" as at least one bit of software I examined used it, but yeah, if there is an author and no authors it should probably at the very least warn in this case.
